### ISSUE TITLE
Error: Cannot find native module 'ExpoGooglePlacesAutocomplete'

### ISSUE THREAD

**Issue by kekoawong** [alanjhughes/expo-google-places-autocomplete#2]
Hello,

Thanks for the great package. I am trying to use the lib since it exposes the functions to build your own component. However, upon installation, I am receiving an error that it cannot find native module 'ExpoGooglePlacesAutocomplete'. This is an expo managed project, so I was under the assumption that I would not have to run npx pod-install. Would this still be necessary in an expo-managed project? My node version is ^17.0.39 and my expo version is ^45.0.0. Thanks.

<img width="628" alt="Screen Shot 2023-01-03 at 4 35 49 PM" src="https://user-images.githubusercontent.com/46762539/210463808-92449c3d-20dc-4187-bb55-4a900b669863.png">

**Comment by alanjhughes** [comment]
Hi, 

You can use it in managed, just not with expo go. You'll need to install it and build a custom dev client
