### ISSUE TITLE
ld: building for iOS Simulator, but linking in object file built for iOS

### ISSUE THREAD

**Issue by dqii** [alanjhughes/expo-google-places-autocomplete#3]
Hi! Excited about this package.

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/19598003/217119525-126a8a7e-0374-4da6-96b0-6903a5680e5e.png">
I'm getting this error at the moment when running EAS Build with SDK 47, both Intel and M1.

**Comment by dqii** [comment]
Running EAS Build with M1 worked!

**Comment by alanjhughes** [comment]
Hi, thanks for reporting. I had been building with expo sdk 47 and it has been working so I'll need to look into this. 

There is also an issue that I should mention in the readme.It cannot be used with with an M1 on the simulator. This is an issue with the GooglePlaces sdk. They do not ship a version compatible with M1 simulators. It should be working on Intel so I'll have to investigate what's going on there 👍

**Comment by dqii** [comment]
Ah, I have an M1 and a simulator, so it sounds like that's the issue. Thanks for letting me know!

Sorry for the confusion --- When I said that the error occurred with both Intel and M1, I meant that it occurred with both Intel and M1 EAS builds.

**Comment by dqii** [comment]
Hi! Just wondering, saw you closed this task -- is this now fixed? Does it work on an M1?

Either way, thank you for your work on this library :)

**Comment by alanjhughes** [comment]
Hi. There's nothing I can do about it for now. Google don't provide an arm64 version so unfortunately you can't run it on the simulator. Not sure why they don't support but I will update if that ever changes

**Comment by dqii** [comment]
No worries, thanks for the reply!
