### ISSUE TITLE
Cannot find native module ExpoGooglePlacesAutocomplete

### ISSUE THREAD

**Issue by webabbey247** [alanjhughes/expo-google-places-autocomplete#4]
I had this issue popping constantly and i decide to check the package folder, i noticed an error which i corrected and it's working now.

After Installation, i noticed this export in ExpoGooglePlacesAutocompleteModule.js
> export default requireNativeModule("ExpoGooglePlacesAutocomplete",) as ExpoGooglePlacesAutocompleteModule;

I removed the comma and everything works fine. The final export is:
> export default requireNativeModule("ExpoGooglePlacesAutocomplete") as ExpoGooglePlacesAutocompleteModule;

**Comment by alanjhughes** [comment]
Thanks! Fixed and published

**Comment by FezVrasta** [comment]
I still see this error installing it from npm, was it published there?

```
 ERROR  Error: Cannot find native module 'ExpoGooglePlacesAutocomplete', js engine: hermes 
```
